macro(add_gtest_dependencies test)
  if (0)
    target_link_libraries(${test} gtest)
    if (${UNIX})
      target_link_libraries(${test} rt)
      target_link_libraries(${test} pthread)
      if (BUILD_SHARED_LIBS)
        target_link_libraries(${test} dl)
      endif()
    endif()
  else()
    target_link_libraries(${test} ${GTEST_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
  endif()
endmacro(add_gtest_dependencies)
